cfg = dict(
    _BASE_=["UCOD-DPL_dinov2.py"],
    exp_name="UCOD-DPL_dinov2_ablation_a1_naive_sam2_20260725_v2",
    dataset_cfg=dict(
        # Generated by offline_sam2_refine.py --mode naive. The 12 samples
        # with empty coarse masks are intentionally handled by pkl fallback.
        refined_pseudo_label_dir="./datasets/cache/naive_sam2_labels",
    ),
)
